spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: Nunam@123
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
