spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/task_manager
    username: postgres
    password: Nunam@123
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
